project_id = "mrpxojsehcqdegiwudru"

[functions.health-chat]
verify_jwt = false

[functions.symptom-checker]
verify_jwt = false

[functions.diet-planner]
verify_jwt = false

[functions.medication-reminder-notification]
verify_jwt = false

[functions.medicine-recommender]
verify_jwt = false
